version: '3'

services:
  test:
    build: .
    volumes:
      - .:/code
    command: actors/test/test_example
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    depends_on:
      - opener_adapter

  opener_adapter:
    build: EIPScanner/docker/opener
    working_dir: /OpENer/bin/posix/src/ports/POSIX
    command: ./OpENer eth0
    ports:
      - "44818:44818"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  opener_adapter2:
    build: EIPScanner/docker/opener
    working_dir: /OpENer/bin/posix/src/ports/POSIX
    command: ./OpENer eth0
    networks:
      testing_net:
        ipv4_address: 172.28.1.7
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16